---
- name: Setup Proxy for Docker (service dir)
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Setup Proxy for Docker (copy service environment)
  template:
    src: ../templates/docker_proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  notify: 
    - restart docker
    - reload systemd