---
- name: restart docker
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
  when: ansible_facts.services.docker.service is defined

- name: reload systemd
  become: yes
  systemd:
    daemon_reload: yes