---
- name: restart docker
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
  when: '"docker.service" in ansible_facts.services'

- name: reload systemd
  become: yes
  systemd:
    daemon_reload: yes