---
- name: Converge
  hosts: all

  vars:
    - http_proxy: http://1.2.3.4:567
    - https_proxy: http://1.2.3.4:567
    - ftp_proxy: http://1.2.3.4:567
  roles:
    - role: ansible-http_proxy_client